spring:
    application:
        name: jpa-demo
    jackson:
        serialization.write_dates_as_timestamps: false
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.66:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: qingshi123
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    mvc:
        favicon:
            enabled: false